# -*- coding: utf-8 -*-

from PySide6 import QtCore, QtGui, QtWidgets
from core.ui.pyab_game_list import _PATH_SHORTCUTS_TOOLTIP, _WATCH_FILE_TOOLTIP, _make_info_btn


class Ui_ProfileList(object):
    def setupUi(self, ProfileList):
        ProfileList.setObjectName("ProfileList")
        ProfileList.resize(1179, 637)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(ProfileList)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, 6, 12, 6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_16 = QtWidgets.QLabel(ProfileList)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.game_list_filter = QtWidgets.QLineEdit(ProfileList)
        self.game_list_filter.setText("")
        self.game_list_filter.setObjectName("game_list_filter")
        self.verticalLayout_3.addWidget(self.game_list_filter)
        self.game_list = QtWidgets.QListWidget(ProfileList)
        self.game_list.setObjectName("game_list")
        self.verticalLayout_3.addWidget(self.game_list)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_15 = QtWidgets.QLabel(ProfileList)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.profile_list = QtWidgets.QListWidget(ProfileList)
        self.profile_list.setObjectName("profile_list")
        self.verticalLayout.addWidget(self.profile_list)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.create_new_btn = QtWidgets.QPushButton(ProfileList)
        self.create_new_btn.setObjectName("create_new_btn")
        self.horizontalLayout_8.addWidget(self.create_new_btn)
        self.dupe_selected_btn = QtWidgets.QPushButton(ProfileList)
        self.dupe_selected_btn.setObjectName("dupe_selected_btn")
        self.horizontalLayout_8.addWidget(self.dupe_selected_btn)
        self.delete_selected_btn = QtWidgets.QPushButton(ProfileList)
        self.delete_selected_btn.setObjectName("delete_selected_btn")
        self.horizontalLayout_8.addWidget(self.delete_selected_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(ProfileList)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name = QtWidgets.QLineEdit(ProfileList)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.label_2 = QtWidgets.QLabel(ProfileList)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.file_name = QtWidgets.QLineEdit(ProfileList)
        self.file_name.setObjectName("file_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.file_name)
        self.label_3 = QtWidgets.QLabel(ProfileList)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.exe_name = QtWidgets.QLineEdit(ProfileList)
        self.exe_name.setObjectName("exe_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.exe_name)
        self.label_4 = QtWidgets.QLabel(ProfileList)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_file_path = QtWidgets.QLineEdit(ProfileList)
        self.save_file_path.setObjectName("save_file_path")
        self.horizontalLayout.addWidget(self.save_file_path)
        self.horizontalLayout.addWidget(_make_info_btn(ProfileList, _PATH_SHORTCUTS_TOOLTIP))
        self.save_file_path_btn = QtWidgets.QToolButton(ProfileList)
        self.save_file_path_btn.setObjectName("save_file_path_btn")
        self.horizontalLayout.addWidget(self.save_file_path_btn)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(ProfileList)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backup_path = QtWidgets.QLineEdit(ProfileList)
        self.backup_path.setObjectName("backup_path")
        self.horizontalLayout_2.addWidget(self.backup_path)
        self.horizontalLayout_2.addWidget(_make_info_btn(ProfileList, _PATH_SHORTCUTS_TOOLTIP))
        self.backup_path_btn = QtWidgets.QToolButton(ProfileList)
        self.backup_path_btn.setObjectName("backup_path_btn")
        self.horizontalLayout_2.addWidget(self.backup_path_btn)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_13 = QtWidgets.QLabel(ProfileList)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.icon = QtWidgets.QLineEdit(ProfileList)
        self.icon.setObjectName("icon")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.icon)
        self.label_6 = QtWidgets.QLabel(ProfileList)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.screenshot_cbox = QtWidgets.QCheckBox(ProfileList)
        self.screenshot_cbox.setObjectName("screenshot_cbox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.screenshot_cbox)
        self.label_7 = QtWidgets.QLabel(ProfileList)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.max_backups_files = QtWidgets.QSpinBox(ProfileList)
        self.max_backups_files.setMaximum(10000)
        self.max_backups_files.setObjectName("max_backups_files")
        self.horizontalLayout_6.addWidget(self.max_backups_files)
        self.label_10 = QtWidgets.QLabel(ProfileList)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 3)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_8 = QtWidgets.QLabel(ProfileList)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.max_size_files = QtWidgets.QSpinBox(ProfileList)
        self.max_size_files.setMaximum(10000000)
        self.max_size_files.setProperty("value", 5000)
        self.max_size_files.setObjectName("max_size_files")
        self.horizontalLayout_5.addWidget(self.max_size_files)
        self.label_9 = QtWidgets.QLabel(ProfileList)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 3)
        self.formLayout.setLayout(9, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_11 = QtWidgets.QLabel(ProfileList)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.auto_backup_timer = QtWidgets.QSpinBox(ProfileList)
        self.auto_backup_timer.setMaximum(3600)
        self.auto_backup_timer.setProperty("value", 120)
        self.auto_backup_timer.setObjectName("auto_backup_timer")
        self.horizontalLayout_7.addWidget(self.auto_backup_timer)
        self.label_12 = QtWidgets.QLabel(ProfileList)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 3)
        self.formLayout.setLayout(10, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_17 = QtWidgets.QLabel(ProfileList)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_14 = QtWidgets.QLabel(ProfileList)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.note = QtWidgets.QPlainTextEdit(ProfileList)
        self.note.setObjectName("note")
        self.horizontalLayout_10.addWidget(self.note)
        self.game_icon = QtWidgets.QLabel(ProfileList)
        self.game_icon.setText("")
        self.game_icon.setObjectName("game_icon")
        self.horizontalLayout_10.addWidget(self.game_icon)
        self.formLayout.setLayout(12, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.watch_line_edit = QtWidgets.QLineEdit(ProfileList)
        self.watch_line_edit.setObjectName("watch_line_edit")
        self.horizontalLayout_9.addWidget(self.watch_line_edit)
        self.horizontalLayout_9.addWidget(_make_info_btn(ProfileList, _WATCH_FILE_TOOLTIP))
        self.label_18 = QtWidgets.QLabel(ProfileList)
        self.label_18.setObjectName("label_18")
        self.label_18.hide()
        self.formLayout.setLayout(11, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.verticalLayout_2.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edit_selected_btn = QtWidgets.QPushButton(ProfileList)
        self.edit_selected_btn.setObjectName("edit_selected_btn")
        self.horizontalLayout_3.addWidget(self.edit_selected_btn)
        self.horizontalLayout_3.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)

        self.retranslateUi(ProfileList)
        QtCore.QMetaObject.connectSlotsByName(ProfileList)

    def retranslateUi(self, ProfileList):
        _translate = QtCore.QCoreApplication.translate
        ProfileList.setWindowTitle(_translate("ProfileList", "Form"))
        self.label_16.setText(_translate("ProfileList", "Games"))
        self.game_list_filter.setPlaceholderText(_translate("ProfileList", "Search by game name..."))
        self.label_15.setText(_translate("ProfileList", "Profiles"))
        self.create_new_btn.setText(_translate("ProfileList", "New Profile"))
        self.dupe_selected_btn.setText(_translate("ProfileList", "Dupe"))
        self.delete_selected_btn.setText(_translate("ProfileList", "Delete"))
        self.label.setText(_translate("ProfileList", "Name:"))
        self.name.setPlaceholderText(_translate("ProfileList", "DSR Vanilla"))
        self.label_2.setText(_translate("ProfileList", "Save File Name:"))
        self.file_name.setPlaceholderText(_translate("ProfileList", "DRAKS0005.sl2"))
        self.label_3.setText(_translate("ProfileList", "Game.exe Name"))
        self.exe_name.setPlaceholderText(_translate("ProfileList", "DarkSoulsRemastered.exe"))
        self.label_4.setText(_translate("ProfileList", "Save File Path:"))
        self.save_file_path.setPlaceholderText(_translate("ProfileList", "#Documents#\\NBGI\\DARK SOULS REMASTERED\\#ID#"))
        self.save_file_path_btn.setText(_translate("ProfileList", "..."))
        self.label_5.setText(_translate("ProfileList", "Backup Path:"))
        self.backup_path.setPlaceholderText(_translate("ProfileList", "PYAB\\Backups\\GameName\\ProfileName\\backup.zip"))
        self.backup_path_btn.setText(_translate("ProfileList", "..."))
        self.label_13.setText(_translate("ProfileList", "Icon:"))
        self.label_6.setText(_translate("ProfileList", "Screenshots:"))
        self.screenshot_cbox.setText(_translate("ProfileList", "Take Screenshots of the game when creating backups."))
        self.label_7.setText(_translate("ProfileList", "Max. Backup Files:"))
        self.label_10.setText(_translate("ProfileList", "Max files before deleting the last backup. Use 0 for unlimited"))
        self.label_8.setText(_translate("ProfileList", "Max. Backups Size:"))
        self.max_size_files.setSuffix(_translate("ProfileList", " MB"))
        self.label_9.setText(_translate("ProfileList", "Max MB before deleting the last backup. Use 0 for unlimited"))
        self.label_11.setText(_translate("ProfileList", "Auto-Backup Timer:"))
        self.auto_backup_timer.setSuffix(_translate("ProfileList", " sec"))
        self.label_12.setText(_translate("ProfileList", "Use 0 for save whenever the save file is updated by the game."))
        self.label_17.setText(_translate("ProfileList", "Watch File:"))
        self.label_14.setText(_translate("ProfileList", "Note:"))
        self.edit_selected_btn.setText(_translate("ProfileList", "Edit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProfileList = QtWidgets.QWidget()
    ui = Ui_ProfileList()
    ui.setupUi(ProfileList)
    ProfileList.show()
    sys.exit(app.exec())
